/**
 * Tiny i18n layer for the TUI chrome. No deps, no ICU — just a flat
 * key → string table per locale with an English fallback chain:
 *
 *   t(key) → STRINGS[locale][key] → STRINGS.en[key] → key
 *
 * A missing key NEVER throws; it renders as the key itself so a typo is
 * visible in the UI instead of crashing a render. Locale detection follows
 * SEEKFORGE_LANG > LC_ALL/LANG (any "zh" prefix → zh-CN) > "en".
 *
 * English values are the canonical UI strings — components and helpers
 * (keyHints, TIPS, status bar, pickers) read through t(), so the en table
 * must stay byte-identical with what tests assert.
 */

export type Locale = "en" | "zh-CN";

/** Number of rotating tips (keys "tips.0" … "tips.N-1"). */
export const TIP_COUNT = 12;

const EN: Record<string, string> = {
  // ── Footer key hints (render-helpers keyHints) ────────────────────────
  "hints.idle": "⏎ send · / commands · @ files · Ctrl+R history",
  "hints.running": "Esc interrupt · Ctrl+B background · ⏎ queue",
  "hints.permission": "y allow · a allow session · A always · n deny",

  // ── Status bar ─────────────────────────────────────────────────────────
  "status.ready": "ready",
  "status.working": "working…",
  "status.interrupt": "esc to interrupt",
  "status.scrolled": "↑ scrolled",

  // ── Header ──────────────────────────────────────────────────────────────
  "tip.prefix": "※",

  // ── Picker / palette footers ────────────────────────────────────────────
  "picker.palette": "↑↓ select · Tab/Enter complete · Esc dismiss",
  "picker.list": "↑↓ select · Enter accept · Esc dismiss",
  "picker.resume": "↑↓ select · Enter resume · / search · r rename · f fork · Esc dismiss",
  "sessions.noMatch": "no session matches the search",
  "sessions.renamePrompt": "name:",
  "sessions.messages": "messages",
  "sessions.firstPrompt": "first prompt",
  "sessions.lastReply": "last reply",
  "sessions.renameFooter": "type a name · Enter save (empty clears it) · Esc cancel",
  "sessions.searchFooter": "type to filter by id, name or task · Enter/Tab back to the list · Esc clear",
  "sessions.renamed": "session renamed:",
  "sessions.nameCleared": "session name cleared:",
  "sessions.renameFailed": "rename failed:",
  "rename.usage": "usage: /rename <title> (names the current session)",
  "rename.noSession": "no session yet — send a message first, or pick one with /sessions",
  "picker.rewind": "↑↓ select · Enter rewind conversation+files · c conversation only · Esc dismiss",
  "picker.model": "↑↓ select · Enter switch · Esc dismiss",
  "picker.history": "↑↓ select · Tab fill · Enter run · Esc dismiss",
  "picker.slash": "↑↓ select · Enter insert · Esc close — @ files · # remember · ! shell · Shift+Tab approval",
  "picker.theme": "↑↓ select · Enter apply · Esc dismiss",
  "picker.candidates": "↑↓ select · a approve · r reject · s scope · Esc dismiss",
  "picker.emptyCommands": "no matching commands",
  "picker.emptyFiles": "no matching files",
  "picker.emptyList": "nothing to show",
  "picker.titleSessions": "Sessions",
  "picker.titleBacktrack": "Backtrack — rewind the conversation to…",
  "picker.titleModel": "Model",
  "picker.titleTheme": "Theme",
  "picker.titleCommands": "Commands",
  "picker.titleCandidates": "Memory candidates — review pending facts",

  // ── ask_user question overlay ─────────────────────────────────────────────
  "question.title": "Question from the agent",
  "question.footerPrefix": "↑↓ or 1-",
  "question.footerSuffix": " select · Enter answer · Esc declines",
  "question.footerFreeText": "type an answer · ↑↓ select · Enter send · Esc declines",

  // ── Sidebar file tree (Ctrl+E) ────────────────────────────────────────────
  "sidebar.title": "Files",
  "sidebar.empty": "(empty)",
  "sidebar.footer": "↑↓ · Enter insert @path · ←→ fold · Ctrl+E close",

  // ── Transcript pager (Ctrl+L) ─────────────────────────────────────────────
  "pager.title": "Transcript",
  "pager.hint": "(q/Esc close · ↑↓/PgUp/PgDn/g/G scroll)",
  "pager.empty": "(transcript is empty)",

  // ── Permission panel ────────────────────────────────────────────────────
  "permission.title": "Permission required",
  "permission.command": "command:",
  "permission.path": "path:",
  "permission.allowOnce": "y allow once",
  "permission.allowSession": "a allow similar commands this session",
  "permission.allowAlways": "A always allow, saved as",
  "permission.saved": "saved permission rule:",
  "permission.saveFailed": "could not save the permission rule (allowed for this session only):",
  "permission.deny": "any other key deny",
  "permission.reviewChange": "Review change:",
  "permission.applyChange": "Apply this change? y accept · n reject",
  "permission.hunk": "Hunk",
  "permission.hunkFooter": "number key toggle hunk · a select all · y confirm · n deny",
  "permission.allowToolSession": "a allow this tool for the rest of the session",
  "permission.denyReason": "N or Tab deny with a reason",
  "permission.reasonPrompt": "Reason (Enter denies with it · Esc goes back):",
  "permission.reviewPlan": "Review:",
  "permission.moreLines": "more lines",
  "permission.ideOpened": "opened the proposed change in",
  "permission.ideFailed": "could not open the diff in the IDE:",
  "permission.ideNone": "no IDE connected — /ide connects one",
  "permission.idePartial": "this preview is partial (a large or multi-file change) — review it here",
  "hints.allow": "y allow",
  "hints.hunks": "1-9 toggle · y apply selection",
  "hints.allowSession": "a allow session",
  "hints.always": "A always",
  "hints.denyReason": "N reason",
  "hints.deny": "n deny",
  "hints.scroll": "↑↓ PgUp PgDn scroll",
  "hints.ideDiff": "o diff in IDE",
  "hints.permissionReason": "type the reason · Enter deny · Esc back",

  // ── Management overlays (/permissions /mcp /agents /hooks /skills /plugins) ─
  "manage.cancelled": "cancelled",
  "manage.failed": "failed:",
  "manage.formFooter": "Tab/↑↓ field · ←→ or Space change a choice · Enter save · Esc cancel",
  "manage.perm.title": "Permission rules — first listed wins within an action",
  "manage.perm.footer": "↑↓ select · a add rule · d delete · Esc close",
  "manage.perm.grantNote": "(this session only)",
  "manage.perm.ignored": "(ignored: a project file cannot allow)",
  "manage.perm.needTool": "a tool name is required (* matches every tool)",
  "manage.perm.projectAllow":
    "the project file may only deny or ask — allow rules there are stripped on load; choose the user scope",
  "manage.perm.readOnly": "read-only here: this rule comes from a --settings file, a profile, or this session",
  "manage.perm.confirmDelete": "press y to delete",
  "manage.perm.fieldTool": "tool",
  "manage.perm.fieldAction": "action",
  "manage.perm.fieldMatch": "match prefix",
  "manage.perm.fieldScope": "save to",
  "manage.perm.added": "added",
  "manage.perm.deleted": "deleted",
  "manage.busy": "a run owns this workspace — try again when it finishes",
  "manage.mcp.title": "MCP servers",
  "manage.mcp.footer":
    "↑↓ select · r reconnect · e enable/disable · a approve · x reject · l copy login command · Esc close",
  "manage.mcp.none": "no MCP servers configured — seekforge mcp add <name> <command> adds one",
  "manage.mcp.untrustedUser": "not enabled: press e to trust it for automatic connection",
  "manage.mcp.disabledOther": "not enabled: its definition does not mark it trusted",
  "manage.mcp.pendingRepo":
    "defined by this repository and not yet approved for this workspace: a reviews and approves it, x rejects it",
  "manage.mcp.rejectedRepo": "rejected for this workspace: a reviews and approves it after all",
  "manage.mcp.loginHint": "OAuth login:",
  "manage.mcp.notEnabled": "this server is not enabled — press e first",
  "manage.mcp.notApproved": "this repository server is not approved for this workspace — press a first",
  "manage.mcp.notRepository": "only a server this repository defines is approved or rejected here",
  "manage.mcp.alreadyApproved": "already approved for this workspace — x rejects it",
  "manage.mcp.alreadyRejected": "already rejected for this workspace",
  "manage.mcp.pluginOwned": "contributed by a plugin — /plugins enables or disables it",
  "manage.mcp.repoOwned": "defined by this repository — a approves it for this workspace, x rejects it",
  "manage.mcp.confirmEnable": "trust and start this server? y confirms —",
  "manage.mcp.reviewDefinition": "the definition this repository asks you to approve (as written, nothing expanded):",
  "manage.mcp.moreLines": "more lines — seekforge mcp get <name> prints all of it",
  "manage.mcp.confirmApprove":
    "approve this exact definition for this workspace and start it? y confirms · any other key cancels",
  "manage.mcp.approved": "approved for this workspace:",
  "manage.mcp.rejected": "rejected for this workspace:",
  "manage.mcp.loginStdio": "stdio servers take no login",
  "manage.mcp.reconnecting": "reconnecting",
  "manage.mcp.enabled": "enabled (saved to your user config):",
  "manage.mcp.disabled": "disabled (saved to your user config):",
  "manage.mcp.copied": "copied:",
  "manage.mcp.runInShell": "run in a shell:",

  // ── Launch, /think, /add-dir, /compact, /rewind, ! passthrough ─────────
  "launch.helperFailedHint": "fix apiKeyHelper in your user config, or set {env} to use a key directly",
  "launch.configHint": "fix the value in your SeekForge config file",
  "arg.think.on": "enable thinking mode",
  "arg.think.off": "disable thinking mode",
  "arg.think.low": "thinking with low reasoning effort",
  "arg.think.medium": "thinking with medium reasoning effort",
  "arg.think.high": "thinking with high reasoning effort",
  "arg.think.max": "thinking with maximum reasoning effort",
  "think.label": "thinking:",
  "think.on": "on",
  "think.off": "off",
  "think.effort": "effort",
  "think.nextMessage": "applies from the next message (each provider sends the effort its endpoint accepts)",
  "addDir.none": "no extra directories — /add-dir <path> grants one to the file tools and @ references",
  "addDir.fromConfig": "(additionalDirectories in your config)",
  "addDir.invalid": "not a directory (or inside the workspace already)",
  "addDir.added":
    "added directory {dir} — from the next message the file tools may read and write there; reference its files with @{dir}/…",
  "compact.hookSays": "hook:",
  "compact.blocked": "compaction cancelled by a preCompact hook:",
  "compact.hookFailed": "compaction hook failed:",
  "compact.busy": "another SeekForge process is using this session — try again when it finishes",
  "rewind.warning": "warning:",
  "rewind.moreWarnings": "more warnings",
  "shell.attached": "attached the output of {n} shell command(s) you ran, as data",
  "agents.noManager": "no subagent has been dispatched in this tab's session",
  "manage.agents.title": "Subagents",
  "manage.agents.footer": "↑↓ select · n new agent · e/Enter open in $EDITOR · Esc close",
  "manage.agents.allTools": "all tools",
  "manage.agents.tools": "tools:",
  "manage.agents.exists": "an agent with this id already exists in that scope",
  "manage.agents.builtin": "built-in agents ship with SeekForge — create one with the same id to override it",
  "manage.agents.noFile": "no editable AGENT.md here (a plugin provides this agent)",
  "manage.agents.fieldId": "id",
  "manage.agents.fieldDescription": "description",
  "manage.agents.fieldTools": "tools (a, b)",
  "manage.agents.fieldMode": "mode",
  "manage.agents.fieldModel": "model",
  "manage.agents.fieldScope": "save to",
  "manage.agents.created": "created",
  "manage.agents.saved": "saved — agents are read at the start of each run:",
  "manage.hooks.title": "Hooks by stage",
  "manage.hooks.footer": "↑↓ scroll · e edit ~/.seekforge/config.json · Esc close",
  "manage.hooks.none": "no hooks configured — repository config cannot add hooks; set them in your user config",
  "manage.skills.title": "Skills",
  "manage.skills.footer": "↑↓ select · Space/Enter enable or disable · Esc close",
  "manage.skills.enabled": "enabled skill",
  "manage.skills.disabled": "disabled skill",
  "manage.plugins.title": "Plugins",
  "manage.plugins.footer": "↑↓ select · Space/Enter enable or disable · Esc close",
  "manage.plugins.invalid": "this plugin failed to load — seekforge plugin inspect <id> shows why",
  "manage.plugins.project":
    "repository plugins are not enabled in place — review it, then seekforge plugin install <path>",
  "manage.plugins.confirmEnable": "enable and approve its current contents? y confirms — it contributes:",
  "manage.plugins.enabled": "enabled plugin",
  "manage.plugins.disabled": "disabled plugin",
  "manage.plugins.restart": "(takes effect when the TUI restarts)",

  // ── IDE bridge (/ide) ─────────────────────────────────────────────────────
  "ide.title": "IDE connections",
  "ide.footer": "↑↓ select · Enter connect · Esc close — /ide off disconnects",
  "ide.none": "no running IDE found — start the SeekForge extension in VS Code",
  "ide.thisWorkspace": "(this workspace)",
  "ide.connected": "connected to",
  "ide.disconnected": "disconnected from the IDE",
  "ide.notConnected": "no IDE connected",
  "ide.attached": "attached IDE context:",
  "ide.contextFailed": "IDE context unavailable:",
  "ide.skipped": "ignored IDE lock file:",
  "ide.status": "IDE",

  // ── Keys ──────────────────────────────────────────────────────────────────
  "keys.header": "Keyboard shortcuts",
  "keys.chord": "waiting for the rest of the chord:",
  "keys.thinkingOn": "thinking on — applies from the next message",
  "keys.thinkingOff": "thinking off — applies from the next message",
  "action.submit": "send the message",
  "action.newline": "insert a newline",
  "action.history-up": "previous prompt",
  "action.history-down": "next prompt",
  "action.cursor-left": "cursor left",
  "action.cursor-right": "cursor right (accepts a suggestion at the end)",
  "action.clear-line": "clear the composer",
  "action.delete-back": "delete backwards",
  "action.delete-forward": "delete forwards",
  "action.external-editor": "edit the prompt in $EDITOR",
  "action.history-search": "search prompt history",
  "action.path-complete": "complete a path",
  "action.paste-image": "paste an image from the clipboard",
  "action.overlay-up": "move up in a picker",
  "action.overlay-down": "move down in a picker",
  "action.overlay-accept": "accept the selection",
  "action.overlay-close": "close the picker",
  "action.cancel-or-quit": "cancel the run, twice to quit",
  "action.cycle-approval": "cycle the approval mode",
  "action.scroll-up": "scroll the transcript up",
  "action.scroll-down": "scroll the transcript down",
  "action.scroll-latest": "jump to the latest message",
  "action.toggle-verbose": "toggle verbose output",
  "action.detach-run": "send the run to the background",
  "action.suspend": "suspend to the shell",
  "action.tab-new": "open a new tab",
  "action.tab-cycle": "switch to the next tab",
  "action.toggle-sidebar": "toggle the file sidebar",
  "action.toggle-pager": "open the transcript pager",
  "action.model-picker": "open the model picker",
  "action.toggle-thinking": "toggle thinking mode",

  // ── Mode line under the composer ────────────────────────────────────────
  "mode.autoApprove": "⏵⏵ auto-approve on",
  "mode.acceptEdits": "⏵ accept-edits on",
  "mode.plan": "⏸ plan mode on",
  "mode.cycleHint": "(shift+tab to cycle)",

  // ── Composer placeholders (app-level; integrator adopts) ───────────────
  "composer.idle": "Ask SeekForge to do something…  (/ commands · @ files · # remember · ! shell)",
  "composer.running": "working… type to queue a follow-up · Esc cancels · ! runs shell",
  "composer.permissionWait": "answer the permission prompt above (y · a · any other key denies)",

  // ── Rotating tips (render-helpers TIPS) ────────────────────────────────
  "tips.0": "Type @ to attach files to your message",
  "tips.1": "Press / to open the command palette",
  "tips.2": "Start a line with # to save a note to project memory",
  "tips.3": "Start a line with ! to run a shell command directly",
  "tips.4": "Ctrl+B detaches the current run to the background",
  "tips.5": "Ctrl+O toggles verbose output (full diffs and tool results)",
  "tips.6": "Press Esc twice to backtrack to an earlier turn",
  "tips.7": "Shift+Tab cycles approval modes (confirm / auto / plan)",
  "tips.8": "Ctrl+R searches your prompt history",
  "tips.9": "/vim enables vim keybindings in the composer",
  "tips.10": "Drop markdown files in .seekforge/commands/ to add custom commands",
  "tips.11": "Ctrl+V pastes an image from the clipboard",

  // ── Slash commands (palette + /help) ──────────────────────────────────
  "cmd.help": "show all commands",
  "cmd.new": "start a fresh session (next message opens it)",
  "cmd.clear": "clear the transcript (name labels the old session)",
  "cmd.sessions": "pick a session to resume — / search, r rename, f fork",
  "cmd.resume": "continue an existing session",
  "cmd.rename": "name the current session (shown in /sessions)",
  "cmd.plan": "plan read-only first, confirm, then execute",
  "cmd.loop": "auto-loop: run→verify until the command passes (task = composer lines below)",
  "cmd.loop-resume": "resume a persisted loop with optional added limits",
  "cmd.loop-list": "list persisted loops in this workspace",
  "cmd.loop-show": "show one persisted loop",
  "cmd.loop-history": "show recent loop lifecycle events",
  "cmd.loop-recover": "mark orphaned loops resumable",
  "cmd.loop-pause": "pause the active loop at its next safe boundary",
  "cmd.loop-continue": "continue the paused loop in this tab",
  "cmd.loop-steer": "guide the active loop at its next safe boundary",
  "cmd.graph-list": "list persisted Engineering Graphs in this workspace",
  "cmd.graph-show": "show one persisted Engineering Graph",
  "cmd.graph-pause": "pause a running Graph at its next safe boundary",
  "cmd.graph-continue": "continue a paused-by-control Graph",
  "cmd.graph-steer": "guide a running Graph at its next safe boundary",
  "cmd.graph-signal": "deliver a wait signal to a Graph",
  "cmd.approve": "show or set the approval mode (Shift+Tab cycles)",
  "cmd.rewind": "undo this session's file changes (dry-run first)",
  "cmd.backtrack": "rewind the conversation to an earlier message (Esc Esc)",
  "cmd.fork": "fork the current session (continue without touching the original)",
  "cmd.tab": "tabs: parallel sessions (Ctrl+N new, Ctrl+T cycle)",
  "cmd.worktree": "git worktree sessions: isolated checkouts under .seekforge/worktrees",
  "cmd.diff": "git diff of the working tree",
  "cmd.review": "review the uncommitted changes (read-only)",
  "cmd.todo": "cross-session todo list (.seekforge/todos.md)",
  "cmd.add-dir": "grant a directory outside the project to the file tools and @ references",
  "cmd.model": "switch model for subsequent messages",
  "cmd.think": "thinking mode and reasoning effort",
  "cmd.remember": "save a fact to project memory (# <fact> also works)",
  "cmd.memory":
    "list project memory facts (candidates reviews pending; keywords backfills bilingual search terms; edit opens a memory file)",
  "cmd.tasks": "background and detached tasks (live; kill stops one)",
  "cmd.agents": "list, create and edit subagents (interactive)",
  "cmd.agent-steer": "guide a running subagent at its next turn",
  "cmd.agent-cancel": "cancel one running subagent",
  "cmd.skills": "enable or disable installed skills (interactive)",
  "cmd.plugins": "enable or disable installed plugins (interactive)",
  "cmd.mcp": "MCP servers: status, reconnect, enable/disable, approve project servers (interactive)",
  "cmd.prompts": "list MCP prompts (invoke as /mcp:<server>:<prompt>)",
  "cmd.init": "analyze the codebase and write/refresh AGENTS.md",
  "cmd.ide": "connect to an IDE: selection and diagnostics context, diffs in the editor",
  "cmd.hooks": "browse configured hooks by stage (e opens the user config)",
  "cmd.doctor": "diagnose the environment (key, node, git, runtime, mcp…)",
  "cmd.status": "session, model, approval and environment at a glance",
  "cmd.release-notes": "show the changelog section for this version",
  "cmd.bug": "copy a bug report (version, doctor, last error) to the clipboard",
  "cmd.config": "show the effective config (edit opens the user config)",
  "cmd.permissions": "permission rules by source: add, delete, session grants (interactive)",
  "cmd.vim": "toggle vim mode for the composer",
  "cmd.mouse": "toggle mouse-wheel scroll (off = native text selection)",
  "cmd.theme": "switch the color theme (deepseek/mono/solarized/matrix…)",
  "cmd.terminal-setup": "how to make Shift+Enter insert a newline in your terminal",
  "cmd.context": "open the context inspector",
  "cmd.compact": "compact the session now (focus steers the LLM summary)",
  "cmd.usage": "cumulative token usage and cost",
  "cmd.balance": "DeepSeek account balance",
  "cmd.export": "export the transcript as markdown",
  "cmd.audit": "write a reviewable audit of a session (timeline, tool calls, files, cost)",
  "cmd.handoff": "write a session handoff document for the next session",
  "cmd.stash": "stash / restore the composer draft",
  "cmd.copy": "copy the last assistant message to the clipboard",
  "cmd.editor": "edit the prompt in $EDITOR (Ctrl+G)",
  "cmd.quit": "exit (Ctrl+C twice also works)",
  "group.session": "Session",
  "group.run": "Running tasks",
  "group.review": "Review & history",
  "group.context": "Context & memory",
  "group.tools": "Tools & surfaces",
  "group.settings": "Settings",
  "group.info": "Info",
};

const ZH_CN: Record<string, string> = {
  "hints.idle": "⏎ 发送 · / 命令 · @ 文件 · Ctrl+R 历史",
  "hints.running": "Esc 中断 · Ctrl+B 转后台 · ⏎ 排队",
  "hints.permission": "y 允许 · a 本会话允许 · A 始终允许 · n 拒绝",

  "status.ready": "就绪",
  "status.working": "处理中…",
  "status.interrupt": "esc 中断",
  "status.scrolled": "↑ 已滚动",

  "tip.prefix": "※",

  "picker.palette": "↑↓ 选择 · Tab/Enter 补全 · Esc 关闭",
  "picker.list": "↑↓ 选择 · Enter 确认 · Esc 关闭",
  "picker.resume": "↑↓ 选择 · Enter 恢复 · / 搜索 · r 重命名 · f 分叉 · Esc 关闭",
  "sessions.noMatch": "没有匹配搜索的会话",
  "sessions.renamePrompt": "名称:",
  "sessions.messages": "条消息",
  "sessions.firstPrompt": "首条提示",
  "sessions.lastReply": "最后回复",
  "sessions.renameFooter": "输入名称 · Enter 保存（留空则清除）· Esc 取消",
  "sessions.searchFooter": "输入以按 id、名称或任务过滤 · Enter/Tab 回到列表 · Esc 清除",
  "sessions.renamed": "会话已重命名:",
  "sessions.nameCleared": "已清除会话名称:",
  "sessions.renameFailed": "重命名失败:",
  "rename.usage": "用法: /rename <标题>（为当前会话命名）",
  "rename.noSession": "还没有会话 — 先发送一条消息，或用 /sessions 选择",
  "picker.rewind": "↑↓ 选择 · Enter 回退对话+文件 · c 仅对话 · Esc 关闭",
  "picker.model": "↑↓ 选择 · Enter 切换 · Esc 关闭",
  "picker.history": "↑↓ 选择 · Tab 填入 · Enter 执行 · Esc 关闭",
  "picker.slash": "↑↓ 选择 · Enter 插入 · Esc 关闭 — @ 文件 · # 记忆 · ! shell · Shift+Tab 审批",
  "picker.theme": "↑↓ 选择 · Enter 应用 · Esc 关闭",
  "picker.candidates": "↑↓ 选择 · a 批准 · r 拒绝 · s 范围 · Esc 关闭",
  "picker.emptyCommands": "无匹配命令",
  "picker.emptyFiles": "无匹配文件",
  "picker.emptyList": "暂无内容",
  "picker.titleSessions": "会话",
  "picker.titleBacktrack": "回退 — 将对话回退到…",
  "picker.titleModel": "模型",
  "picker.titleTheme": "主题",
  "picker.titleCommands": "命令",
  "picker.titleCandidates": "记忆候选 — 审阅待定事实",

  "question.title": "来自代理的提问",
  "question.footerPrefix": "↑↓ 或 1-",
  "question.footerSuffix": " 选择 · Enter 回答 · Esc 拒绝",
  "question.footerFreeText": "直接输入答案 · ↑↓ 选择 · 回车提交 · esc 拒绝",

  "sidebar.title": "文件",
  "sidebar.empty": "（空）",
  "sidebar.footer": "↑↓ · Enter 插入 @path · ←→ 折叠 · Ctrl+E 关闭",

  "pager.title": "记录",
  "pager.hint": "(q/Esc 关闭 · ↑↓/PgUp/PgDn/g/G 滚动)",
  "pager.empty": "（记录为空）",

  "permission.title": "需要授权",
  "permission.command": "命令:",
  "permission.path": "路径:",
  "permission.allowOnce": "y 允许一次",
  "permission.allowSession": "a 本会话允许同类命令",
  "permission.allowAlways": "A 始终允许，将写入规则",
  "permission.saved": "已保存授权规则:",
  "permission.saveFailed": "授权规则保存失败（本次会话仍然允许）:",
  "permission.deny": "其他键拒绝",
  "permission.reviewChange": "审查变更:",
  "permission.applyChange": "应用此变更? y 接受 · n 拒绝",
  "permission.hunk": "代码块",
  "permission.hunkFooter": "数字键切换代码块 · a 全选 · y 确认 · n 拒绝",
  "permission.allowToolSession": "a 本会话内允许此工具",
  "permission.denyReason": "N 或 Tab 附理由拒绝",
  "permission.reasonPrompt": "拒绝理由（Enter 带理由拒绝 · Esc 返回）:",
  "permission.reviewPlan": "审阅:",
  "permission.moreLines": "行未显示",
  "permission.ideOpened": "已在 IDE 中打开拟议改动:",
  "permission.ideFailed": "无法在 IDE 中打开 diff:",
  "permission.ideNone": "未连接 IDE — 用 /ide 连接",
  "permission.idePartial": "该预览不完整（改动较大或涉及多个文件）— 请在此处审阅",
  "hints.allow": "y 允许",
  "hints.hunks": "1-9 切换 · y 应用所选",
  "hints.allowSession": "a 本会话允许",
  "hints.always": "A 始终允许",
  "hints.denyReason": "N 附理由",
  "hints.deny": "n 拒绝",
  "hints.scroll": "↑↓ PgUp PgDn 滚动",
  "hints.ideDiff": "o 在 IDE 看 diff",
  "hints.permissionReason": "输入理由 · Enter 拒绝 · Esc 返回",

  "manage.cancelled": "已取消",
  "manage.failed": "失败:",
  "manage.formFooter": "Tab/↑↓ 切换字段 · ←→ 或空格切换选项 · Enter 保存 · Esc 取消",
  "manage.perm.title": "授权规则 — 同一动作内先列出的优先",
  "manage.perm.footer": "↑↓ 选择 · a 添加规则 · d 删除 · Esc 关闭",
  "manage.perm.grantNote": "（仅本会话）",
  "manage.perm.ignored": "（被忽略：项目配置不能放行）",
  "manage.perm.needTool": "需要填写工具名（* 匹配所有工具）",
  "manage.perm.projectAllow": "项目配置只能 deny 或 ask — 其中的 allow 规则会在加载时被剔除；请选择用户范围",
  "manage.perm.readOnly": "此处只读：该规则来自 --settings 文件、profile 或本会话",
  "manage.perm.confirmDelete": "按 y 删除",
  "manage.perm.fieldTool": "工具",
  "manage.perm.fieldAction": "动作",
  "manage.perm.fieldMatch": "匹配前缀",
  "manage.perm.fieldScope": "保存到",
  "manage.perm.added": "已添加",
  "manage.perm.deleted": "已删除",
  "manage.busy": "有运行正在占用此工作区 — 请在它结束后重试",
  "manage.mcp.title": "MCP 服务器",
  "manage.mcp.footer": "↑↓ 选择 · r 重连 · e 启用/停用 · a 批准 · x 拒绝 · l 复制登录命令 · Esc 关闭",
  "manage.mcp.none": "未配置 MCP 服务器 — seekforge mcp add <name> <command> 可添加",
  "manage.mcp.untrustedUser": "未启用：按 e 信任它以便自动连接",
  "manage.mcp.disabledOther": "未启用：其定义没有标记为受信任",
  "manage.mcp.pendingRepo": "由本仓库定义，尚未在此工作区获批：按 a 审阅并批准，按 x 拒绝",
  "manage.mcp.rejectedRepo": "已在此工作区被拒绝：按 a 可重新审阅并批准",
  "manage.mcp.loginHint": "OAuth 登录:",
  "manage.mcp.notEnabled": "该服务器未启用 — 先按 e",
  "manage.mcp.notApproved": "该仓库服务器尚未在此工作区获批 — 先按 a",
  "manage.mcp.notRepository": "只有本仓库定义的服务器才能在这里批准或拒绝",
  "manage.mcp.alreadyApproved": "已在此工作区获批 — 按 x 可拒绝",
  "manage.mcp.alreadyRejected": "已在此工作区被拒绝",
  "manage.mcp.pluginOwned": "由插件提供 — 在 /plugins 中启用或停用",
  "manage.mcp.repoOwned": "由本仓库定义 — 按 a 在此工作区批准，按 x 拒绝",
  "manage.mcp.confirmEnable": "信任并启动此服务器？按 y 确认 —",
  "manage.mcp.reviewDefinition": "本仓库请求你批准的定义（原样显示，未展开任何引用）：",
  "manage.mcp.moreLines": "行未显示 — seekforge mcp get <name> 可查看全部",
  "manage.mcp.confirmApprove": "在此工作区批准这份定义并启动它？按 y 确认 · 其他任意键取消",
  "manage.mcp.approved": "已在此工作区批准:",
  "manage.mcp.rejected": "已在此工作区拒绝:",
  "manage.mcp.loginStdio": "stdio 服务器无需登录",
  "manage.mcp.reconnecting": "正在重连",
  "manage.mcp.enabled": "已启用（已写入用户配置）:",
  "manage.mcp.disabled": "已停用（已写入用户配置）:",
  "manage.mcp.copied": "已复制:",
  "manage.mcp.runInShell": "请在 shell 中运行:",

  // ── 启动、/think、/add-dir、/compact、/rewind、! 直通 ──────────────────
  "launch.helperFailedHint": "修正用户配置中的 apiKeyHelper，或设置 {env} 直接使用密钥",
  "launch.configHint": "修正 SeekForge 配置文件中的这个值",
  "arg.think.on": "开启思考模式",
  "arg.think.off": "关闭思考模式",
  "arg.think.low": "思考，低推理强度",
  "arg.think.medium": "思考，中等推理强度",
  "arg.think.high": "思考，高推理强度",
  "arg.think.max": "思考，最高推理强度",
  "think.label": "思考:",
  "think.on": "开",
  "think.off": "关",
  "think.effort": "强度",
  "think.nextMessage": "从下一条消息起生效（各提供方按其端点支持的级别发送）",
  "addDir.none": "没有额外目录 — /add-dir <path> 可把一个目录授权给文件工具和 @ 引用",
  "addDir.fromConfig": "（来自配置中的 additionalDirectories）",
  "addDir.invalid": "不是目录（或已在工作区内）",
  "addDir.added": "已添加目录 {dir} — 从下一条消息起，文件工具可以在其中读写；用 @{dir}/… 引用其中的文件",
  "compact.hookSays": "钩子:",
  "compact.blocked": "压缩被 preCompact 钩子取消:",
  "compact.hookFailed": "压缩钩子运行失败:",
  "compact.busy": "另一个 SeekForge 进程正在使用此会话 — 等它结束后再试",
  "rewind.warning": "警告:",
  "rewind.moreWarnings": "条警告未显示",
  "shell.attached": "已附上你运行的 {n} 条 shell 命令的输出（作为数据）",
  "agents.noManager": "本标签页的会话还没有派发过子智能体",
  "manage.agents.title": "子智能体",
  "manage.agents.footer": "↑↓ 选择 · n 新建 · e/Enter 在 $EDITOR 中打开 · Esc 关闭",
  "manage.agents.allTools": "全部工具",
  "manage.agents.tools": "工具:",
  "manage.agents.exists": "该范围内已存在同 id 的智能体",
  "manage.agents.builtin": "内置智能体随 SeekForge 提供 — 新建同 id 的智能体即可覆盖",
  "manage.agents.noFile": "这里没有可编辑的 AGENT.md（该智能体由插件提供）",
  "manage.agents.fieldId": "id",
  "manage.agents.fieldDescription": "描述",
  "manage.agents.fieldTools": "工具 (a, b)",
  "manage.agents.fieldMode": "模式",
  "manage.agents.fieldModel": "模型",
  "manage.agents.fieldScope": "保存到",
  "manage.agents.created": "已创建",
  "manage.agents.saved": "已保存 — 智能体在每次运行开始时读取:",
  "manage.hooks.title": "按阶段列出的钩子",
  "manage.hooks.footer": "↑↓ 滚动 · e 编辑 ~/.seekforge/config.json · Esc 关闭",
  "manage.hooks.none": "未配置钩子 — 仓库配置不能添加钩子；请在用户配置中设置",
  "manage.skills.title": "技能",
  "manage.skills.footer": "↑↓ 选择 · 空格/Enter 启用或停用 · Esc 关闭",
  "manage.skills.enabled": "已启用技能",
  "manage.skills.disabled": "已停用技能",
  "manage.plugins.title": "插件",
  "manage.plugins.footer": "↑↓ 选择 · 空格/Enter 启用或停用 · Esc 关闭",
  "manage.plugins.invalid": "该插件加载失败 — seekforge plugin inspect <id> 可查看原因",
  "manage.plugins.project": "仓库内的插件不能原地启用 — 审阅后执行 seekforge plugin install <path>",
  "manage.plugins.confirmEnable": "启用并批准其当前内容？按 y 确认 — 它提供:",
  "manage.plugins.enabled": "已启用插件",
  "manage.plugins.disabled": "已停用插件",
  "manage.plugins.restart": "（重启 TUI 后生效）",

  "ide.title": "IDE 连接",
  "ide.footer": "↑↓ 选择 · Enter 连接 · Esc 关闭 — /ide off 断开",
  "ide.none": "未发现运行中的 IDE — 请在 VS Code 中启动 SeekForge 扩展",
  "ide.thisWorkspace": "（本工作区）",
  "ide.connected": "已连接到",
  "ide.disconnected": "已断开 IDE 连接",
  "ide.notConnected": "未连接 IDE",
  "ide.attached": "已附带 IDE 上下文:",
  "ide.contextFailed": "无法获取 IDE 上下文:",
  "ide.skipped": "已忽略的 IDE 锁文件:",
  "ide.status": "IDE",

  "keys.header": "键盘快捷键",
  "keys.chord": "等待组合键的后续按键:",
  "keys.thinkingOn": "思考已开启 — 从下一条消息起生效",
  "keys.thinkingOff": "思考已关闭 — 从下一条消息起生效",
  "action.submit": "发送消息",
  "action.newline": "插入换行",
  "action.history-up": "上一条提示",
  "action.history-down": "下一条提示",
  "action.cursor-left": "光标左移",
  "action.cursor-right": "光标右移（行尾时接受补全建议）",
  "action.clear-line": "清空输入框",
  "action.delete-back": "向前删除",
  "action.delete-forward": "向后删除",
  "action.external-editor": "在 $EDITOR 中编辑提示",
  "action.history-search": "搜索提示历史",
  "action.path-complete": "补全路径",
  "action.paste-image": "从剪贴板粘贴图片",
  "action.overlay-up": "选择器中上移",
  "action.overlay-down": "选择器中下移",
  "action.overlay-accept": "确认选择",
  "action.overlay-close": "关闭选择器",
  "action.cancel-or-quit": "取消运行，连按两次退出",
  "action.cycle-approval": "切换审批模式",
  "action.scroll-up": "向上滚动记录",
  "action.scroll-down": "向下滚动记录",
  "action.scroll-latest": "跳到最新消息",
  "action.toggle-verbose": "切换详细输出",
  "action.detach-run": "将运行转入后台",
  "action.suspend": "挂起到 shell",
  "action.tab-new": "新建标签页",
  "action.tab-cycle": "切换到下一个标签页",
  "action.toggle-sidebar": "切换文件侧栏",
  "action.toggle-pager": "打开记录分页器",
  "action.model-picker": "打开模型选择器",
  "action.toggle-thinking": "切换思考模式",

  "mode.autoApprove": "⏵⏵ 自动批准已开启",
  "mode.acceptEdits": "⏵ 自动接受编辑已开启",
  "mode.plan": "⏸ 计划模式已开启",
  "mode.cycleHint": "(shift+tab 切换)",

  "composer.idle": "让 SeekForge 做点什么…  (/ 命令 · @ 文件 · # 记忆 · ! shell)",
  "composer.running": "处理中… 输入可排队后续消息 · Esc 取消 · ! 运行 shell",
  "composer.permissionWait": "请回答上方的授权提示（y · a · 其他键拒绝）",

  "tips.0": "输入 @ 将文件附加到消息",
  "tips.1": "按 / 打开命令面板",
  "tips.2": "以 # 开头的行会存入项目记忆",
  "tips.3": "以 ! 开头的行直接运行 shell 命令",
  "tips.4": "Ctrl+B 将当前运行转入后台",
  "tips.5": "Ctrl+O 切换详细输出（完整 diff 与工具结果）",
  "tips.6": "连按两次 Esc 回退到更早的轮次",
  "tips.7": "Shift+Tab 循环切换审批模式（确认 / 自动 / 计划）",
  "tips.8": "Ctrl+R 搜索提示历史",
  "tips.9": "/vim 在输入框启用 vim 键位",
  "tips.10": "在 .seekforge/commands/ 放置 markdown 文件可添加自定义命令",
  "tips.11": "Ctrl+V 从剪贴板粘贴图片",

  // ── Slash commands (palette + /help) ──────────────────────────────────
  "cmd.help": "显示全部命令",
  "cmd.new": "开始新会话（下一条消息将开启它）",
  "cmd.clear": "清空对话记录（name 用于标记旧会话）",
  "cmd.sessions": "选择一个会话恢复 — / 搜索，r 重命名，f 分叉",
  "cmd.resume": "继续一个已有会话",
  "cmd.rename": "为当前会话命名（在 /sessions 中显示）",
  "cmd.plan": "先只读地规划，确认后再执行",
  "cmd.loop": "自动循环：run→verify 直到命令通过（任务写在下方输入框）",
  "cmd.loop-resume": "恢复一个已持久化的 loop，可追加限制",
  "cmd.loop-list": "列出本工作区已持久化的 loop",
  "cmd.loop-show": "查看某个已持久化的 loop",
  "cmd.loop-history": "查看最近的 loop 生命周期事件",
  "cmd.loop-recover": "把孤立的 loop 标记为可恢复",
  "cmd.loop-pause": "在下一个安全边界暂停当前 loop",
  "cmd.loop-continue": "在本标签页继续已暂停的 loop",
  "cmd.loop-steer": "在下一个安全边界引导当前 loop",
  "cmd.graph-list": "列出本工作区已持久化的工程 Graph",
  "cmd.graph-show": "查看某个已持久化的工程 Graph",
  "cmd.graph-pause": "在下一个安全边界暂停运行中的 Graph",
  "cmd.graph-continue": "继续被控制命令暂停的 Graph",
  "cmd.graph-steer": "在下一个安全边界引导运行中的 Graph",
  "cmd.graph-signal": "向 Graph 投递一个等待信号",
  "cmd.approve": "查看或设置审批模式（Shift+Tab 循环切换）",
  "cmd.rewind": "撤销本会话的文件改动（先 dry-run）",
  "cmd.backtrack": "把对话回退到更早的一条消息（Esc Esc）",
  "cmd.fork": "复刻当前会话（继续推进而不影响原会话）",
  "cmd.tab": "标签页：并行会话（Ctrl+N 新建，Ctrl+T 切换）",
  "cmd.worktree": "git worktree 会话：位于 .seekforge/worktrees 的隔离检出",
  "cmd.diff": "工作树的 git diff",
  "cmd.review": "审查未提交的改动（只读）",
  "cmd.todo": "跨会话待办清单（.seekforge/todos.md）",
  "cmd.add-dir": "把项目外的一个目录授权给文件工具和 @ 引用",
  "cmd.model": "为后续消息切换模型",
  "cmd.think": "思考模式与推理强度",
  "cmd.remember": "把一条事实存入项目记忆（用 # <事实> 也可以）",
  "cmd.memory": "列出项目记忆事实（candidates 审阅待定项；keywords 补齐双语检索词；edit 打开记忆文件）",
  "cmd.tasks": "后台与分离任务（实时；kill 可终止其一）",
  "cmd.agents": "列出、创建和编辑子智能体（交互式）",
  "cmd.agent-steer": "在下一轮引导某个运行中的子智能体",
  "cmd.agent-cancel": "取消某个运行中的子智能体",
  "cmd.skills": "启用或停用已安装的技能（交互式）",
  "cmd.plugins": "启用或停用已安装的插件（交互式）",
  "cmd.mcp": "MCP 服务器：状态、重连、启用/停用、批准项目服务器（交互式）",
  "cmd.prompts": "列出 MCP 提示词（以 /mcp:<server>:<prompt> 调用）",
  "cmd.init": "分析代码库并写入/刷新 AGENTS.md",
  "cmd.ide": "连接 IDE：附带选区与诊断上下文，在编辑器中查看 diff",
  "cmd.hooks": "按阶段浏览已配置的钩子（e 打开用户配置）",
  "cmd.doctor": "诊断运行环境（key、node、git、runtime、mcp…）",
  "cmd.status": "一览会话、模型、审批模式与运行环境",
  "cmd.release-notes": "显示当前版本的更新日志",
  "cmd.bug": "把问题报告（版本、doctor、最近错误）复制到剪贴板",
  "cmd.config": "显示生效配置（edit 打开用户配置）",
  "cmd.permissions": "按来源管理授权规则：添加、删除、查看会话授权（交互式）",
  "cmd.vim": "切换输入框的 vim 模式",
  "cmd.mouse": "切换鼠标滚轮滚动（关闭后可用原生文本选择）",
  "cmd.theme": "切换配色主题（deepseek/mono/solarized/matrix…）",
  "cmd.terminal-setup": "如何让 Shift+Enter 在你的终端里插入换行",
  "cmd.context": "打开上下文检查器",
  "cmd.compact": "立即压缩会话（focus 可引导 LLM 摘要）",
  "cmd.usage": "累计 token 用量与花费",
  "cmd.balance": "DeepSeek 账户余额",
  "cmd.export": "把对话记录导出为 markdown",
  "cmd.audit": "为某个会话写出可审阅的审计报告（时间线、工具调用、文件、花费）",
  "cmd.handoff": "为下一个会话写一份交接文档",
  "cmd.stash": "暂存 / 恢复输入框草稿",
  "cmd.copy": "复制最后一条助手消息到剪贴板",
  "cmd.editor": "在 $EDITOR 中编辑提示词（Ctrl+G）",
  "cmd.quit": "退出（连按两次 Ctrl+C 也可以）",
  "group.session": "会话",
  "group.run": "运行任务",
  "group.review": "审查与历史",
  "group.context": "上下文与记忆",
  "group.tools": "工具与界面",
  "group.settings": "设置",
  "group.info": "信息",
};

/** All UI strings, keyed by locale then string key. en is canonical. */
export const STRINGS: Record<Locale, Record<string, string>> = {
  en: EN,
  "zh-CN": ZH_CN,
};

let currentLocale: Locale = "en";

/**
 * Detect the UI locale from the environment. Precedence:
 * SEEKFORGE_LANG (explicit override) > LC_ALL > LANG; any value whose
 * lowercase form starts with "zh" selects zh-CN, everything else is en.
 */
export function detectLocale(env: Record<string, string | undefined> = process.env): Locale {
  const explicit = env.SEEKFORGE_LANG;
  if (explicit) return explicit.toLowerCase().startsWith("zh") ? "zh-CN" : "en";
  for (const value of [env.LC_ALL, env.LANG]) {
    if (value?.toLowerCase().startsWith("zh")) return "zh-CN";
  }
  return "en";
}

/** Set the active locale (called once at startup; takes effect immediately). */
export function setLocale(l: Locale): void {
  currentLocale = l;
}

/** The currently active locale. */
export function getLocale(): Locale {
  return currentLocale;
}

/**
 * Translate `key` for the active locale. Falls back to English, then to the
 * key itself — never throws, so a missing translation degrades gracefully.
 */
export function t(key: string): string {
  return STRINGS[currentLocale][key] ?? STRINGS.en[key] ?? key;
}

/**
 * Translate `key`, falling back to a caller-supplied string rather than to the
 * key itself. For text that already exists in English at its definition site —
 * the slash-command registry, whose summaries are part of how that module
 * reads — so the English does not have to be written twice to stay authoritative.
 */
export function translate(key: string, fallback: string): string {
  return STRINGS[currentLocale][key] ?? fallback;
}
